language: cpp
compiler:
  - clang
  - gcc
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y libusb-1.0-0 libusb-1.0-0-dev libftdi1 libftdi-dev root-system* root-plugin*; fi
script: 
  - mkdir build && cd build/
  - cmake ..
  - make install
branches:
  only:
    - master
os:
  - linux