language: cpp
compiler:
  - clang
  - gcc
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y libusb-1.0-0 libusb-1.0-0-dev libftdi1 libftdi-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then sudo port install libusb; fi
before_script:
  - sudo wget http://downloads.sourceforge.net/project/cernrootdebs/latest-recommended/root_5.34.07-1_amd64.deb
  - sudo dpkg --install root_5.34.07-1_amd64.deb
  - echo $ROOTSYS
script: 
  - mkdir build && cd build/
  - cmake ..
  - make install
branches:
  only:
    - master
os:
  - linux