language: cpp
compiler:
  - clang
  - gcc
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y libusb-1.0-0 libusb-1.0-0-dev libftdi1 libftdi-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then sudo port install libusb; fi
before_script:
  - echo "deb http://lcg-heppkg.web.cern.ch/lcg-heppkg/debian sid hep" | sudo tee -a /etc/apt/sources.list
  - echo "deb-src http://lcg-heppkg.web.cern.ch/lcg-heppkg/debian sid hep" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install root-system
script: 
  - mkdir build && cd build/
  - cmake -DBUILD_pxarui=OFF ..
  - make install
branches:
  only:
    - master
os:
  - linux